# Generated by Django 5.1.7 on 2025-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_product_count_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
